name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nicoverbruggen/fntbld-oci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build release artifacts
        run: python3 build.py --out-dir out

      - name: Create zip files
        run: |
          cd out/kobo/core    && zip -j /tmp/kobo-core-fonts.zip *.ttf
          cd $GITHUB_WORKSPACE/out/kobo/extra   && zip -j /tmp/kobo-extra-fonts.zip *.ttf
          cd $GITHUB_WORKSPACE/out/sources/core  && zip -j /tmp/other-core-fonts.zip *.ttf
          cd $GITHUB_WORKSPACE/out/sources/extra && zip -j /tmp/other-extra-fonts.zip *.ttf

      - name: Create draft release
        uses: akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.GITEA_TOKEN }}
          draft: true
          tag_name: ${{ inputs.version || gitea.ref_name }}
          name: NV Collection (${{ inputs.version || gitea.ref_name }})
          body: |
            > [!TIP]
            > **If you are using a Kobo device and reading books purchased from the Kobo Store or reading `kepub` files converted via Calibre**, you should download the Kobo Collection (`kobo-core-fonts.zip`, `kobo-extra-fonts.zip`), which has fonts slightly altered for optimal kerning for the `kepub` renderer.

            ### Learn more

            For more information about the fonts, screenshots and how to install them, please consult the README. The FAQ also includes an entry on how to enable ligatures on Kobo devices, which is highly recommended.

            ### License

            Due to the nature of the OFL/libre licensing of the fonts, you may find these or the original fonts also excellent for embedding in your digital books in lieu of a commercial font, which may be prohibitively expensive to license if you wish to distribute your own epub files.

            More info about licensing information can be found in the FAQ, which is part of the README.
          files: |
            /tmp/kobo-core-fonts.zip
            /tmp/kobo-extra-fonts.zip
            /tmp/other-core-fonts.zip
            /tmp/other-extra-fonts.zip
